camel:
  springboot:
    # The Camel context name
    name: CamelRestJpa
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /artificial-intelligence-restservice/*

logging:
  level:
    root: INFO

spring:
   main:
     allow-bean-definition-overriding: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s